### ISSUE TITLE
希望能像彩云天气那样，把很多传感器单独放出来额

### ISSUE THREAD

**Issue by Seifon** [shaonianzhentan/hf_weather#9]
比如温度，湿度

**Comment by shaonianzhentan** [comment]
温湿度在实体属性中，如有需要可以自行使用官方模板实体自定义

**Comment by bionexit** [comment]
> 比如温度，湿度

这样加一个sensor就好

```
- platform: template
  sensors:
    air_quatlity_index:
      friendly_name: "AQI"
      value_template: "{{ float(state_attr('weather.tjweather','aqi').aqi)}}"
      unique_id: asd023
```
